# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'iOSCrashlyticsTest' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!


# Add the pod for Firebase Crashlytics
pod 'Firebase/Crashlytics'

# Recommended: Add the Firebase pod for Google Analytics
pod 'Firebase/Analytics'


  # Pods for iOSCrashlyticsTest

  target 'iOSCrashlyticsTestTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'iOSCrashlyticsTestUITests' do
    # Pods for testing
  end

end
